# Generated by Django 2.0.5 on 2018-05-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reward',
            new_name='ExchangeItem',
        ),
        migrations.AddField(
            model_name='vendor',
            name='contract_address',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.TextField(unique=True),
        ),
    ]
