# Generated by Django 2.0.5 on 2018-05-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0002_auto_20180503_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.TextField(max_length=128),
        ),
    ]
