# Generated by Django 2.0.5 on 2018-05-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0003_auto_20180503_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangeitem',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
