# Generated by Django 2.0.5 on 2018-05-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0004_auto_20180504_0112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExchangeItem',
            new_name='Reward',
        ),
    ]
