# Generated by Django 2.0.5 on 2018-05-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0005_auto_20180504_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='wallet_address',
            field=models.TextField(default='123456789', max_length=128),
            preserve_default=False,
        ),
    ]
