# Generated by Django 2.0.5 on 2018-05-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0006_vendor_wallet_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='contract_address',
        ),
    ]
