# Generated by Django 2.0.5 on 2018-05-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0007_remove_vendor_contract_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='wallet_address',
            new_name='contract_address',
        ),
    ]
